#ifndef GRPRESETS_H
#define GRPRESETS_H


#define NAME_MAIN_PRESETS   "_kb2dConfigs.preset"
#define _ENUM_(name, base) enum name : base

_ENUM_(MainPresetList, int)
{
    // Detection Settings
    Main_HWGain,
    Main_NBeamsX,
    Main_Fps,
    Main_Threshold,
    Main_DetSpeed,
    Main_DetSelectivity,
    Main_Deviation,
            Main_DeviationFilter,
    Main_OffRelease,

    // Height Settings
    Main_ModulationTypeZ,
    Main_InvertZ,
    Main_SmoothZ,
    Main_AttackZ,
    Main_AmplitudeZ,
    Main_StabZ,
            Main_MinZ,
            Main_MediumZ,
            Main_MaxZ,
            Main_SubZ,

            // X Vars
            Main_MinPosX,
            Main_MaxPosX,
            Main_SubPosX,
            Main_InvertPosX,

            Main_MinWidthX,
            Main_MaxWidthX,
            Main_SubWidthX,
            Main_InvertWidthX,

            Main_MinGlideX,
            Main_MaxGlideX,
            Main_SubGlideX,
            Main_InvertGlideX,
            Main_StabGlideX,

            Main_EnableSub11,
            Main_EnableSub12,
            Main_EnableSub31,
            Main_EnableSub32,
            Main_EnableSub41,
            Main_EnableSub42,

    // Angles
    Main_AngleZ0X0,
    Main_AngleZ0X1,
    Main_AngleZ0X2,
    Main_AngleZ0X3,
    Main_AngleZ0X4,
    Main_AngleZ0X5,
    Main_AngleZ0X6,
    Main_AngleZ0X7,
    Main_AngleZ0X8,
    Main_AngleZ0X9,
    Main_AngleZ0X10,
    Main_AngleZ0X11,
    Main_AngleZ0X12,
    Main_AngleZ0X13,
    Main_AngleZ0X14,
    Main_AngleZ0X15,

    //MIDI Settings
    // Port 1
    Midi_BeamEnabled,
    Midi_SendOnClick,
    Midi_FirstKey,
    Midi_NbKey,
    Midi_EnableNotes,
    Midi_EnableEffect1,
    Midi_EnableEffect2,
    Midi_DescEffect1,
    Midi_DescEffect2,
    Midi_NoteChan,
    Midi_NoteNote,
    Midi_NoteVel,
    Midi_Eff1Chan,
    Midi_Eff1Ctrl,
    Midi_Eff1Val,
    Midi_Eff2Chan,
    Midi_Eff2Ctrl,
    Midi_Eff2Val,
    Midi_Note0,
    Midi_Note1,
    Midi_Note2,
    Midi_Note3,
    Midi_Note4,
    Midi_Note5,
    Midi_Note6,
    Midi_Note7,
    Midi_Note8,
    Midi_Note9,
    Midi_Note10,
    Midi_Note11,
    Midi_Note12,
    Midi_Note13,
    Midi_Note14,
    Midi_Note15,

    // Port 3
    Midi_BeamEnabled_3P,
    Midi_SendOnClick_3P,
    Midi_FirstKey_3P,
    Midi_NbKey_3P,
    Midi_EnableNotes_3P,
    Midi_EnableEffect1_3P,
    Midi_EnableEffect2_3P,
    Midi_DescEffect1_3P,
    Midi_DescEffect2_3P,
    Midi_NoteChan_3P,
    Midi_NoteNote_3P,
    Midi_NoteVel_3P,
    Midi_Eff1Chan_3P,
    Midi_Eff1Ctrl_3P,
    Midi_Eff1Val_3P,
    Midi_Eff2Chan_3P,
    Midi_Eff2Ctrl_3P,
    Midi_Eff2Val_3P,
    Midi_Note0_3P,
    Midi_Note1_3P,
    Midi_Note2_3P,
    Midi_Note3_3P,
    Midi_Note4_3P,
    Midi_Note5_3P,
    Midi_Note6_3P,
    Midi_Note7_3P,
    Midi_Note8_3P,
    Midi_Note9_3P,
    Midi_Note10_3P,
    Midi_Note11_3P,
    Midi_Note12_3P,
    Midi_Note13_3P,
    Midi_Note14_3P,
    Midi_Note15_3P,

    // Port 4
    Midi_BeamEnabled_4P,
    Midi_SendOnClick_4P,
    Midi_FirstKey_4P,
    Midi_NbKey_4P,
    Midi_EnableNotes_4P,
    Midi_EnableEffect1_4P,
    Midi_EnableEffect2_4P,
    Midi_DescEffect1_4P,
    Midi_DescEffect2_4P,
    Midi_NoteChan_4P,
    Midi_NoteNote_4P,
    Midi_NoteVel_4P,
    Midi_Eff1Chan_4P,
    Midi_Eff1Ctrl_4P,
    Midi_Eff1Val_4P,
    Midi_Eff2Chan_4P,
    Midi_Eff2Ctrl_4P,
    Midi_Eff2Val_4P,
    Midi_Note0_4P,
    Midi_Note1_4P,
    Midi_Note2_4P,
    Midi_Note3_4P,
    Midi_Note4_4P,
    Midi_Note5_4P,
    Midi_Note6_4P,
    Midi_Note7_4P,
    Midi_Note8_4P,
    Midi_Note9_4P,
    Midi_Note10_4P,
    Midi_Note11_4P,
    Midi_Note12_4P,
    Midi_Note13_4P,
    Midi_Note14_4P,
    Midi_Note15_4P,

    Main_NumParam
};

#endif // GRPRESETS_H
